const BY_BRANCH = 1;
const BY_DISTRIBUTION_CENTER = 2;
const BY_BRANCH_AND_DISTRIBUTION_CENTER = 3;
const BY_BRANCH_OR_DISTRIBUTION_CENTER = 4;

module.exports = {
  BY_BRANCH,
  BY_DISTRIBUTION_CENTER,
  BY_BRANCH_AND_DISTRIBUTION_CENTER,
  BY_BRANCH_OR_DISTRIBUTION_CENTER
}
